<link rel="stylesheet" href="styles/content.css"/>
<div class="content-view">
    <div class="content-view_sections">
        <div class="content-view_card-div">

            <?php
            $desavanja = json_decode(DesavanjeModel::getAll());
            foreach ($desavanja as $desavanje) {
                $date = getdate( strtotime( $desavanje->Datetime ) );
            ?>
            <div class="card">
                <div class="card-img">
                    <h2 class="card-img_text"><?php echo $date['mday'];?> <br> <?php echo $date['month'];?> </h2>
                </div>
                <div class="card-text">
                    <div>
                        <h3><?php echo $desavanje->Ime;?></h3>
                        <p><?php echo $desavanje->Opis;?></p>
                    </div>
                </div>
            </div>

            <?php } ?>

        </div>
    </div>
</div>