<link rel="stylesheet" href="styles/content.css"/>
<div class="content-view">
    <div class="content-view_sections">
        <div class="content-view_card-div">
            <div class="card">
                        <div class="card-img">
                            <h2 class="card-img_text">16 <br> JUL</h2>
                        </div>
                        <div class="card-text">
                            <div>
                                <h3>Neki dogadjaj- Super zezanje idk sta jos</h3>
                                <p>Lokacija eventa - koliko sati</p>
                            </div>
                            <div class="card-info">
                                <p>19:20</p>
                                <p>169din</p>
                            </div>
                        </div>
                    </div>
            <div class="card">
                        <div class="card-img">
                            <h2 class="card-img_text">16 <br> JUL</h2>
                        </div>
                        <div class="card-text">
                            <div>
                                <h3>Neki dogadjaj- Super zezanje idk sta jos</h3>
                                <p>Lokacija eventa - koliko sati</p>
                            </div>
                            <div class="card-info">
                                <p>19:20</p>
                                <p>169din</p>
                            </div>
                        </div>
                    </div>
            <div class="card">
                        <div class="card-img">
                            <h2 class="card-img_text">16 <br> JUL</h2>
                        </div>
                        <div class="card-text">
                            <div>
                                <h3>Neki dogadjaj- Super zezanje idk sta jos</h3>
                                <p>Lokacija eventa - koliko sati</p>
                            </div>
                            <div class="card-info">
                                <p>19:20</p>
                                <p>169din</p>
                            </div>
                        </div>
                    </div>
            <div class="card">
                        <div class="card-img">
                            <h2 class="card-img_text">16 <br> JUL</h2>
                        </div>
                        <div class="card-text">
                            <div>
                                <h3>Neki dogadjaj- Super zezanje idk sta jos</h3>
                                <p>Lokacija eventa - koliko sati</p>
                            </div>
                            <div class="card-info">
                                <p>19:20</p>
                                <p>169din</p>
                            </div>
                        </div>
                    </div>
        </div>
        <div class="content-view_card-div">
            <div class="card">
                        <div class="card-img">
                            <h2 class="card-img_text">16 <br> JUL</h2>
                        </div>
                        <div class="card-text">
                            <div>
                                <h3>Neki dogadjaj- Super zezanje idk sta jos</h3>
                                <p>Lokacija eventa - koliko sati</p>
                            </div>
                            <div class="card-info">
                                <p>19:20</p>
                                <p>169din</p>
                            </div>
                        </div>
                    </div>
            <div class="card">
                        <div class="card-img">
                            <h2 class="card-img_text">16 <br> JUL</h2>
                        </div>
                        <div class="card-text">
                            <div>
                                <h3>Neki dogadjaj- Super zezanje idk sta jos</h3>
                                <p>Lokacija eventa - koliko sati</p>
                            </div>
                            <div class="card-info">
                                <p>19:20</p>
                                <p>169din</p>
                            </div>
                        </div>
                    </div>
            <div class="card">
                        <div class="card-img">
                            <h2 class="card-img_text">16 <br> JUL</h2>
                        </div>
                        <div class="card-text">
                            <div>
                                <h3>Neki dogadjaj- Super zezanje idk sta jos</h3>
                                <p>Lokacija eventa - koliko sati</p>
                            </div>
                            <div class="card-info">
                                <p>19:20</p>
                                <p>169din</p>
                            </div>
                        </div>
                    </div>
            <div class="card">
                        <div class="card-img">
                            <h2 class="card-img_text">16 <br> JUL</h2>
                        </div>
                        <div class="card-text">
                            <div>
                                <h3>Neki dogadjaj- Super zezanje idk sta jos</h3>
                                <p>Lokacija eventa - koliko sati</p>
                            </div>
                            <div class="card-info">
                                <p>19:20</p>
                                <p>169din</p>
                            </div>
                        </div>
                    </div>
        </div>
        <div class="content-view_card-div">
            <div class="card">
                        <div class="card-img">
                            <h2 class="card-img_text">16 <br> JUL</h2>
                        </div>
                        <div class="card-text">
                            <div>
                                <h3>Neki dogadjaj- Super zezanje idk sta jos</h3>
                                <p>Lokacija eventa - koliko sati</p>
                            </div>
                            <div class="card-info">
                                <p>19:20</p>
                                <p>169din</p>
                            </div>
                        </div>
                    </div>
            <div class="card">
                        <div class="card-img">
                            <h2 class="card-img_text">16 <br> JUL</h2>
                        </div>
                        <div class="card-text">
                            <div>
                                <h3>Neki dogadjaj- Super zezanje idk sta jos</h3>
                                <p>Lokacija eventa - koliko sati</p>
                            </div>
                            <div class="card-info">
                                <p>19:20</p>
                                <p>169din</p>
                            </div>
                        </div>
                    </div>
            <div class="card">
                        <div class="card-img">
                            <h2 class="card-img_text">16 <br> JUL</h2>
                        </div>
                        <div class="card-text">
                            <div>
                                <h3>Neki dogadjaj- Super zezanje idk sta jos</h3>
                                <p>Lokacija eventa - koliko sati</p>
                            </div>
                            <div class="card-info">
                                <p>19:20</p>
                                <p>169din</p>
                            </div>
                        </div>
                    </div>
            <div class="card">
                        <div class="card-img">
                            <h2 class="card-img_text">16 <br> JUL</h2>
                        </div>
                        <div class="card-text">
                            <div>
                                <h3>Neki dogadjaj- Super zezanje idk sta jos</h3>
                                <p>Lokacija eventa - koliko sati</p>
                            </div>
                            <div class="card-info">
                                <p>19:20</p>
                                <p>169din</p>
                            </div>
                        </div>
                    </div>
        </div>
    </div>
</div>