<!DOCTYPE html>
<html lang="en">
<head>
	<base href="/localhost" />
	<meta charset="UTF-8" />
	<title><?= $title ?></title>
	<link rel="stylesheet" href="styles.css" type="text/css"/>
	<script src="https://cdn.jsdelivr.net/npm/darkmode-js@1.5.3/lib/darkmode-js.min.js"></script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
	<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script src="scripts/sidebar.js"></script>
</head>
<body>
	<div class="is-desktop">
		<div class="navi">
			<p class="navi_logo"><span class="navi_red-txt">okulturi</span>.me</p>
			<ul>
				<li><a href="/home"> Home </a></li>
				<li><a > Kultura </a></li>
				<li><a href="/login"> Login </a></li>
				<li><a href="/register"> Registracija </a></li>
			</ul>
		</div>
		<?php $this->controller->renderView();?>
	</div>

	<div class="is-mobile">
		<div id="mySidebar" class="sidebar">
			<a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
			<a href="/home"> Home </a>
			<a> Kultura </a>
			<a href="/login"> Login </a>
			<a href="/register"> Registracija </a>
		</div>

		<div id="main">
			<!-- TODO TOP BAR -->
			<button class="openbtn" onclick="openNav()">&#9776;</button>
			<?php $this->controller->renderView();?>
		</div>
	</div>
	
	<script>
	var options = {
		bottom: '64px', // default: '32px'
		right: '32px', // default: '32px'
		left: 'unset', // default: 'unset'
		time: '0.5s', // default: '0.3s'
		mixColor: '#fff', // default: '#fff'
		backgroundColor: '#fff',  // default: '#fff'
		buttonColorDark: '#100f2c',  // default: '#100f2c'
		buttonColorLight: '#fff', // default: '#fff'
		saveInCookies: true, // default: true,
		label: '🌓', // default: ''
		autoMatchOsTheme: true // default: true
	}

	const darkmode = new Darkmode(options);
	darkmode.showWidget();
	</script>
	
	<script src="scripts/mobileCheck.js"></script>
</body>
</html>
