<!DOCTYPE html>
<html lang="en">
<head>
	<base href="/localhost" />
	<meta charset="UTF-8" />
	<title><?= $title ?></title>
	<link rel="stylesheet" href="styles.css" type="text/css"/>
</head>
<body>
	<div class="navi">
		<p><span>okulturi</span>.me</p>
		<ul>
			<li>Home</li>
			<li>Kultura</li>
			<li>O nama</li>
			<li>Novosti</li>
			<li>Log in</li>
		</ul>
	</div>
	<?php $this->controller->renderView();?>

	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</body>
</html>
