<!DOCTYPE html>
<html lang="en">
<head>
	<base href="/localhost" />
	<meta charset="UTF-8" />
	<title><?= $title ?></title>
	<link rel="stylesheet" href="styles.css" type="text/css"/>
	<script src="https://cdn.jsdelivr.net/npm/darkmode-js@1.5.3/lib/darkmode-js.min.js"></script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
	<div class="is-desktop">
		<div class="navi">
			<p class="navi_logo"><span class="navi_red-txt">okulturi</span>.me</p>
			<ul>
				<li><a href="/home">Home</a></li>
				<li><a href="">Kultura</a></li>
				<li><a href="">O nama</a></li>
				<li><a href="">Novosti</a></li>
				<li><a href="/login">Log in</a></li>
			</ul>
		</div>
		<?php $this->controller->renderView();?>
	</div>

	<div class="is-mobile">
		<?php $this->controller->renderView();?>
	</div>
	
	<script>
	var options = {
		bottom: '64px', // default: '32px'
		right: '32px', // default: '32px'
		left: 'unset', // default: 'unset'
		time: '0.5s', // default: '0.3s'
		mixColor: '#fff', // default: '#fff'
		backgroundColor: '#fff',  // default: '#fff'
		buttonColorDark: '#100f2c',  // default: '#100f2c'
		buttonColorLight: '#fff', // default: '#fff'
		saveInCookies: true, // default: true,
		label: '🌓', // default: ''
		autoMatchOsTheme: true // default: true
	}

	const darkmode = new Darkmode(options);
	darkmode.showWidget();
	</script>
	
</body>
</html>
