<link rel="stylesheet" href="styles/login.css" />
<div class="login-view">
    <div class="login-view_heading">
        <h2>Welcome Back!</h2>
        <p>Ulogujte se da bi ste videli sva najnovija desavanja.</p>
        <div class="login-view_body">
            <div class="login-view_body-left">
                <div class="login-view_form">
                    <h3>Uloguj se</h3>
                    <div class="input-field col s6">
                        <input id="last_name" type="text" class="validate">
                        <label for="last_name">Email Adresa</label>
                    </div>
                    <div class="input-field col s12">
                        <input id="password" type="password" class="validate">
                        <label for="password">Password</label>
                    </div>
                    <div>
                        <a class="button">LOG IN</a>
                    </div>
                    <a href=""> Nemate svoj profil? Registrujte se!</a>
                </div>
            </div>
            <!-- Right Div -->
            <div class="login-view_body-right">
                <div class="login-view_events">
                    <h3>Preporucena desavanja</h3>
                    <!--Cards-->
                    <div class="card">
  <div class="card-img">
    <h2>16 <br> JUL</h2>
  </div>
  <div class="card-text">
    <div>
     <h3>Neki dogadjaj- Super zezanje idk sta jos</h3>
    <p>Lokacija eventa - koliko sati</p>
      </div>
    <div class="card-info">
     <p>19:20</p>
    <p>169din</p>
      </div>
  </div>
</div>


<div class="card">
  <div class="card-img">
    <h2>16 <br> JUL</h2>
  </div>
  <div class="card-text">
    <div>
     <h3>Neki dogadjaj- Super zezanje idk sta jos</h3>
    <p>Lokacija eventa - koliko sati</p>
      </div>
    <div class="card-info">
     <p>19:20</p>
    <p>169din</p>
      </div>
  </div>
</div>



<div class="card">
  <div class="card-img">
    <h2>16 <br> JUL</h2>
  </div>
  <div class="card-text">
    <div>
     <h3>Neki dogadjaj- Super zezanje idk sta jos</h3>
    <p>Lokacija eventa - koliko sati</p>
      </div>
    <div class="card-info">
     <p>19:20</p>
    <p>169din</p>
      </div>
  </div>
</div>
                </div>
            </div>
        </div>
    </div>
</div>