<link rel="stylesheet" href="styles/moja-desavanja.css"/>
<div class="moja-desavanja-view">
<div class="moja-desavanja-view_sections">
        <div class="moja-desavanja-view_card-div">
            <h2>Moja Desavanja</h2>


        <!--Ovo se Replicira-->
            <div class="card">
                <div class="card-img">
                    <h2 class="card-img_text">16. <br>
                JUL</h2>
                </div>
                <div class="card-text">
                    <div>
                        <h3>Skroz Super Naslov</h3>
                        <p>Deskripcija</p>
                    </div>
                </div>
            </div>
<!--Ovo se Replicira-->

        </div>
    </div>
</div>