<link rel="stylesheet" href="styles/novo-desavanje.css" />
<div class="novo-desavanje-view">
    <div class="novo-desavanje_div">
        <form action="">
        <h1 class="novo-desavanje_div-heading">KREIRAJ SVOJ DOGADJAJ</h1>
        <div class="input-field">
                        <input id="email" type="text" class="validate">
                        <label for="email">Tip Dogadjaja</label>
                    </div>
                    <div class="input-field">
                        <input id="email" type="text" class="validate">
                        <label for="email">Naziv dogadjaja</label>
                    </div>
                    <div class="input-field">
                        <input id="email" type="text" class="validate">
                        <label for="email">Mesto odrzavanja</label>
                    </div>
                    <div class="input-field">
                        <input id="email" type="date" class="validate">
                        <label for="email">Datum odrzavanja</label>
                    </div>
    
    <a class="novo-desavanje_div-button" href="#">Postavi sliku dogadjaja</a>
    <br>
    <a class="novo-desavanje_div-button" href="#">Postavi Dogadjaj</a>
    </form>
</div>
</div>