<link rel="stylesheet" href="styles/login.css" />
<div class="login-view">
    <div class="login-view_heading">
        <div class="login-view_body">
            <form action="">
                <div class="login-view_form">
                    <h3 class="login-view_body-heading">Registruj se</h3>
                    <h4 class="login-view_body-subheading">Registrujte se da bi ste videli sva najnovija desavanja.</h4>
                    <div class="input-field col s6">
                        <input id="last_name" type="text" class="validate">
                        <label for="last_name">Ime i Prezime</label>
                    </div>
                    <div class="input-field col s6">
                        <input id="last_name" type="text" class="validate">
                        <label for="last_name">Email Adresa</label>
                    </div>
                    <div class="input-field col s12">
                        <input id="password" type="password" class="validate">
                        <label for="password">Password</label>
                    </div>
                    <div class="login-view_form-button">
                        <a class="button">REGISTER</a>
                    </div>
                    <div>
                    <a href="/register"> Zelite li da primate nase newsletter mejlove?</a>
                    </div>
                </div>
            </div>
            </form>
    </div>
</div>