<link rel="stylesheet" href="styles/register.css" />
<script src="scripts/register.js"></script>
<div class="register-view">
    <div class="register-view_heading">
        <div class="register-view_body">
            <form action="">
                <div class="register-view_form">
                    <h3 class="register-view_body-heading">Registruj se</h3>
                    <h4 class="register-view_body-subheading">Registrujte se da bi ste videli sva <br>
                    najnovija desavanja.</h4>
                    <div class="input-field col s6">
                        <input type="text" id="nameField" class="validate">
                        <label for="nameField">Ime i Prezime</label>
                    </div>
                    <div class="input-field col s6">
                        <input type="text" id="emailField" class="validate">
                        <label for="emailField">Email Adresa</label>
                    </div>
                    <div class="input-field col s12">
                        <input type="password" id="passwordField" class="validate">
                        <label for="passwordField">Password</label>
                    </div>
                    <div class="input-field col s12">
                        <input type="password" id="repeatPasswordField" class="validate">
                        <label for="repeatPasswordField">Confirm Password</label>
                    </div>
                    <div class="register-view_form-button">
                        <a class="button" type="button" id="registerBtn">REGISTER</a>
                    </div>
                </div>
            </div>
            </form>
    </div>
</div>